<?php
	global $default_settings_mint;
	$default_settings_mint=array(
		'indexformat' => 1,
		'scrolling' => 1,
		'navmenu_default' => 0,
		'navt_font' =>'google',
		'navmenu_tfontg' =>'Montserrat',
		'navmenu_tfontgw' =>'regular',
		'navmenu_color' => '#326693',
		'navmenu_fsize' => '15',
		'actnavbg_default' => 1,
		'section_element' => '2',
		'sectitle_default' => 0,
		'sect_font' => 'google',
		'sectitle_color' => '#3c3c3c',
		'sectitle_fontg' => 'Montserrat',
		'sectitle_fontgw' => '700',
		'sectitle_fontgsubset' => '',
		'sectitle_fsize' => '31',
		'seccont_default' => 0,
		'seccont_color' => '#333333',
		'secc_font' => 'google',
		'seccont_fontg'	=> 'PT+Sans',
		'seccont_fontgw' => 'regular',
		'seccont_fsize' => '15',
		'related_doc' => 1,
		'scroll_color' => '#326693',
		'iconscroll' => '1',
		'togglemenu' => '0',
		'guidetitle' => '0',
	);
?>
